"""
alembic/env.py — Async-compatible Alembic environment for SQLAlchemy 2.0.

Key differences from the default env.py generated by `alembic init`:
  1. Uses async_engine_from_config + run_sync pattern for async engine compatibility
  2. Imports Base + all ORM models so autogenerate detects schema
  3. Overrides sqlalchemy.url from backend.config.settings (respects .env)
"""
import asyncio
import os
import sys
from logging.config import fileConfig

# ---------------------------------------------------------------------------
# Path fix: when alembic runs from d:/TaxMantri/backend/, the parent directory
# (d:/TaxMantri/) must be on sys.path so `from backend.xxx import yyy` resolves.
# ---------------------------------------------------------------------------
_here = os.path.dirname(os.path.abspath(__file__))           # .../backend/alembic/
_backend_dir = os.path.dirname(_here)                         # .../backend/
_project_root = os.path.dirname(_backend_dir)                 # .../TaxMantri/
if _project_root not in sys.path:
    sys.path.insert(0, _project_root)

from alembic import context
from sqlalchemy import pool
from sqlalchemy.ext.asyncio import async_engine_from_config

# Import Base first — defines the metadata object
from backend.database import Base

# Import all ORM models so their tables register on Base.metadata
# noqa: F401 — imports are side-effects (registration), not used directly
import backend.models  # noqa: F401

# Override the sqlalchemy.url from our settings (reads .env)
from backend.config import settings

# Alembic Config object — access to values in alembic.ini
config = context.config

# Set URL from settings (overrides alembic.ini sqlalchemy.url)
config.set_main_option("sqlalchemy.url", settings.database_url)

# Configure Python logging from alembic.ini [loggers] section
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Metadata for autogenerate support
target_metadata = Base.metadata


# ---------------------------------------------------------------------------
# Offline migrations (generates SQL without connecting)
# ---------------------------------------------------------------------------
def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode — outputs SQL without a live connection."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


# ---------------------------------------------------------------------------
# Online migrations (connects to database and applies changes)
# ---------------------------------------------------------------------------
def do_run_migrations(connection) -> None:
    context.configure(connection=connection, target_metadata=target_metadata)
    with context.begin_transaction():
        context.run_migrations()


async def run_migrations_online() -> None:
    """Run migrations in 'online' mode — connects and applies to live database."""
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,  # NullPool for migrations — no persistent connections
    )
    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)
    await connectable.dispose()


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_migrations_online())
